package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campana generated by hbm2java
 */
public class Campana  implements java.io.Serializable {


     private Integer idCampana;
     private String nombre;
     private Set<Ejecutivo> ejecutivos = new HashSet<Ejecutivo>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Pagina> paginas = new HashSet<Pagina>(0);

    public Campana() {
    }

	
    public Campana(String nombre) {
        this.nombre = nombre;
    }
    public Campana(String nombre, Set<Ejecutivo> ejecutivos, Set<Solicitud> solicituds, Set<Pagina> paginas) {
       this.nombre = nombre;
       this.ejecutivos = ejecutivos;
       this.solicituds = solicituds;
       this.paginas = paginas;
    }
   
    public Integer getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(Integer idCampana) {
        this.idCampana = idCampana;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Ejecutivo> getEjecutivos() {
        return this.ejecutivos;
    }
    
    public void setEjecutivos(Set<Ejecutivo> ejecutivos) {
        this.ejecutivos = ejecutivos;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Pagina> getPaginas() {
        return this.paginas;
    }
    
    public void setPaginas(Set<Pagina> paginas) {
        this.paginas = paginas;
    }




}


