package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejecutivo generated by hbm2java
 */
public class Ejecutivo  implements java.io.Serializable {


     private Integer idEjecutivo;
     private Area area;
     private Aseguradora aseguradora;
     private Campana campana;
     private Ejecutivo ejecutivo;
     private String usuario;
     private String nombre;
     private String correo;
     private String password;
     private Byte estado;
     private Date fechaIngreso;
     private Date fechaBaja;
     private String comment;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Ejecutivo> ejecutivos = new HashSet<Ejecutivo>(0);

    public Ejecutivo() {
    }

	
    public Ejecutivo(Campana campana, String usuario, Date fechaIngreso) {
        this.campana = campana;
        this.usuario = usuario;
        this.fechaIngreso = fechaIngreso;
    }
    public Ejecutivo(Area area, Aseguradora aseguradora, Campana campana, Ejecutivo ejecutivo, String usuario, String nombre, String correo, String password, Byte estado, Date fechaIngreso, Date fechaBaja, String comment, Set<Solicitud> solicituds, Set<Ejecutivo> ejecutivos) {
       this.area = area;
       this.aseguradora = aseguradora;
       this.campana = campana;
       this.ejecutivo = ejecutivo;
       this.usuario = usuario;
       this.nombre = nombre;
       this.correo = correo;
       this.password = password;
       this.estado = estado;
       this.fechaIngreso = fechaIngreso;
       this.fechaBaja = fechaBaja;
       this.comment = comment;
       this.solicituds = solicituds;
       this.ejecutivos = ejecutivos;
    }
   
    public Integer getIdEjecutivo() {
        return this.idEjecutivo;
    }
    
    public void setIdEjecutivo(Integer idEjecutivo) {
        this.idEjecutivo = idEjecutivo;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Aseguradora getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(Aseguradora aseguradora) {
        this.aseguradora = aseguradora;
    }
    public Campana getCampana() {
        return this.campana;
    }
    
    public void setCampana(Campana campana) {
        this.campana = campana;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Ejecutivo> getEjecutivos() {
        return this.ejecutivos;
    }
    
    public void setEjecutivos(Set<Ejecutivo> ejecutivos) {
        this.ejecutivos = ejecutivos;
    }




}


