package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1



/**
 * MarcaCliente generated by hbm2java
 */
public class MarcaCliente  implements java.io.Serializable {


     private Integer idMarcaCliente;
     private String nombre;
     private String clave;
     private Integer idAseguradora;

    public MarcaCliente() {
    }

	
    public MarcaCliente(String nombre, String clave) {
        this.nombre = nombre;
        this.clave = clave;
    }
    public MarcaCliente(String nombre, String clave, Integer idAseguradora) {
       this.nombre = nombre;
       this.clave = clave;
       this.idAseguradora = idAseguradora;
    }
   
    public Integer getIdMarcaCliente() {
        return this.idMarcaCliente;
    }
    
    public void setIdMarcaCliente(Integer idMarcaCliente) {
        this.idMarcaCliente = idMarcaCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Integer getIdAseguradora() {
        return this.idAseguradora;
    }
    
    public void setIdAseguradora(Integer idAseguradora) {
        this.idAseguradora = idAseguradora;
    }




}


