package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pagina generated by hbm2java
 */
public class Pagina  implements java.io.Serializable {


     private Integer idPagina;
     private Aseguradora aseguradora;
     private Campana campana;
     private String url;
     private String descripcion;
     private int status;
     private Date fechaRegistro;
     private Date fechaActualizacion;
     private Date fechaUltimoCorte;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Pagina() {
    }

	
    public Pagina(Campana campana, int status, Date fechaRegistro) {
        this.campana = campana;
        this.status = status;
        this.fechaRegistro = fechaRegistro;
    }
    public Pagina(Aseguradora aseguradora, Campana campana, String url, String descripcion, int status, Date fechaRegistro, Date fechaActualizacion, Date fechaUltimoCorte, Set<Solicitud> solicituds) {
       this.aseguradora = aseguradora;
       this.campana = campana;
       this.url = url;
       this.descripcion = descripcion;
       this.status = status;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaUltimoCorte = fechaUltimoCorte;
       this.solicituds = solicituds;
    }
   
    public Integer getIdPagina() {
        return this.idPagina;
    }
    
    public void setIdPagina(Integer idPagina) {
        this.idPagina = idPagina;
    }
    public Aseguradora getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(Aseguradora aseguradora) {
        this.aseguradora = aseguradora;
    }
    public Campana getCampana() {
        return this.campana;
    }
    
    public void setCampana(Campana campana) {
        this.campana = campana;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Date getFechaUltimoCorte() {
        return this.fechaUltimoCorte;
    }
    
    public void setFechaUltimoCorte(Date fechaUltimoCorte) {
        this.fechaUltimoCorte = fechaUltimoCorte;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


