package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Campana campana;
     private Ejecutivo ejecutivo;
     private Pagina pagina;
     private StatusSolicitud statusSolicitud;
     private TipoContacto tipoContacto;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String telefono;
     private String correo;
     private String cp;
     private Date anio;
     private String marca;
     private String submarca;
     private String modelo;
     private String cve;
     private String cobertura;
     private BigDecimal primaTotal;
     private String comentarios;
     private Date fechaSolicitud;
     private Date fechaNacimiento;
     private Character sexo;

    public Solicitud() {
    }

	
    public Solicitud(Campana campana, StatusSolicitud statusSolicitud, TipoContacto tipoContacto, String nombre, String telefono, String correo, String cp, Date anio, String marca, String modelo, String comentarios, Date fechaSolicitud) {
        this.campana = campana;
        this.statusSolicitud = statusSolicitud;
        this.tipoContacto = tipoContacto;
        this.nombre = nombre;
        this.telefono = telefono;
        this.correo = correo;
        this.cp = cp;
        this.anio = anio;
        this.marca = marca;
        this.modelo = modelo;
        this.comentarios = comentarios;
        this.fechaSolicitud = fechaSolicitud;
    }
    public Solicitud(Campana campana, Ejecutivo ejecutivo, Pagina pagina, StatusSolicitud statusSolicitud, TipoContacto tipoContacto, String nombre, String apellidoPaterno, String apellidoMaterno, String telefono, String correo, String cp, Date anio, String marca, String submarca, String modelo, String cve, String cobertura, BigDecimal primaTotal, String comentarios, Date fechaSolicitud, Date fechaNacimiento, Character sexo) {
       this.campana = campana;
       this.ejecutivo = ejecutivo;
       this.pagina = pagina;
       this.statusSolicitud = statusSolicitud;
       this.tipoContacto = tipoContacto;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.telefono = telefono;
       this.correo = correo;
       this.cp = cp;
       this.anio = anio;
       this.marca = marca;
       this.submarca = submarca;
       this.modelo = modelo;
       this.cve = cve;
       this.cobertura = cobertura;
       this.primaTotal = primaTotal;
       this.comentarios = comentarios;
       this.fechaSolicitud = fechaSolicitud;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Campana getCampana() {
        return this.campana;
    }
    
    public void setCampana(Campana campana) {
        this.campana = campana;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public Pagina getPagina() {
        return this.pagina;
    }
    
    public void setPagina(Pagina pagina) {
        this.pagina = pagina;
    }
    public StatusSolicitud getStatusSolicitud() {
        return this.statusSolicitud;
    }
    
    public void setStatusSolicitud(StatusSolicitud statusSolicitud) {
        this.statusSolicitud = statusSolicitud;
    }
    public TipoContacto getTipoContacto() {
        return this.tipoContacto;
    }
    
    public void setTipoContacto(TipoContacto tipoContacto) {
        this.tipoContacto = tipoContacto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getSubmarca() {
        return this.submarca;
    }
    
    public void setSubmarca(String submarca) {
        this.submarca = submarca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCve() {
        return this.cve;
    }
    
    public void setCve(String cve) {
        this.cve = cve;
    }
    public String getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }
    public BigDecimal getPrimaTotal() {
        return this.primaTotal;
    }
    
    public void setPrimaTotal(BigDecimal primaTotal) {
        this.primaTotal = primaTotal;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }




}


