package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SubmarcaCliente generated by hbm2java
 */
public class SubmarcaCliente  implements java.io.Serializable {


     private Integer idSubmarcaCliente;
     private Integer idAseguradora;
     private String nombre;
     private String clave;
     private String camis;
     private String tipo;
     private Date anio;
     private Integer idMarcaCliente;

    public SubmarcaCliente() {
    }

	
    public SubmarcaCliente(String nombre) {
        this.nombre = nombre;
    }
    public SubmarcaCliente(Integer idAseguradora, String nombre, String clave, String camis, String tipo, Date anio, Integer idMarcaCliente) {
       this.idAseguradora = idAseguradora;
       this.nombre = nombre;
       this.clave = clave;
       this.camis = camis;
       this.tipo = tipo;
       this.anio = anio;
       this.idMarcaCliente = idMarcaCliente;
    }
   
    public Integer getIdSubmarcaCliente() {
        return this.idSubmarcaCliente;
    }
    
    public void setIdSubmarcaCliente(Integer idSubmarcaCliente) {
        this.idSubmarcaCliente = idSubmarcaCliente;
    }
    public Integer getIdAseguradora() {
        return this.idAseguradora;
    }
    
    public void setIdAseguradora(Integer idAseguradora) {
        this.idAseguradora = idAseguradora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getCamis() {
        return this.camis;
    }
    
    public void setCamis(String camis) {
        this.camis = camis;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public Integer getIdMarcaCliente() {
        return this.idMarcaCliente;
    }
    
    public void setIdMarcaCliente(Integer idMarcaCliente) {
        this.idMarcaCliente = idMarcaCliente;
    }




}


