package models;
// Generated 20/06/2016 12:09:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoContacto generated by hbm2java
 */
public class TipoContacto  implements java.io.Serializable {


     private Byte idTipoContacto;
     private String descripcion;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public TipoContacto() {
    }

    public TipoContacto(String descripcion, Set<Solicitud> solicituds) {
       this.descripcion = descripcion;
       this.solicituds = solicituds;
    }
   
    public Byte getIdTipoContacto() {
        return this.idTipoContacto;
    }
    
    public void setIdTipoContacto(Byte idTipoContacto) {
        this.idTipoContacto = idTipoContacto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


